/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chan_ypatchcore_YPatch */

#ifndef _Included_com_chan_ypatchcore_YPatch
#define _Included_com_chan_ypatchcore_YPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chan_ypatchcore_YPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_chan_ypatchcore_YPatch_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
